#!/bin/bash

# WhisperLiveKit Server Scripts Overview
# Lists all available run scripts with their configurations

echo "🚀 WhisperLiveKit Server Scripts Overview"
echo "========================================"
echo ""
echo "Available run scripts for different configurations:"
echo ""

echo "📋 Script List:"
echo "==============="
echo ""

echo "1. run_server.sh"
echo "   - Base script with default medium model"
echo "   - Configurable with any whisperlivekit-server options"
echo "   - Usage: ./run_server.sh [options]"
echo ""

echo "2. run_server_small.sh"
echo "   - Small model (fastest processing, lower accuracy)"
echo "   - No diarization for maximum speed"
echo "   - Usage: ./run_server_small.sh [options]"
echo ""

echo "3. run_server_medium.sh"
echo "   - Medium model (balanced speed/accuracy)"
echo "   - No diarization for faster processing"
echo "   - Usage: ./run_server_medium.sh [options]"
echo ""

echo "4. run_server_large.sh"
echo "   - Large-v3 model (highest accuracy, multilingual)"
echo "   - No diarization for faster processing"
echo "   - Usage: ./run_server_large.sh [options]"
echo ""

echo "5. run_server_with_diarization_large_id.sh"
echo "   - Large-v3 model with diarization (speaker identification)"
echo "   - Optimized for Indonesian language"
echo "   - Usage: ./run_server_with_diarization_large_id.sh [options]"
echo ""

echo "6. run_server_english.sh"
echo "   - Medium model optimized for English language"
echo "   - Language set to English (en)"
echo "   - Usage: ./run_server_english.sh [options]"
echo ""

echo "7. run_server_multilingual.sh"
echo "   - Large-v3 model with diarization for multilingual support"
echo "   - Automatic language detection"
echo "   - Usage: ./run_server_multilingual.sh [options]"
echo ""

echo "8. run_server_network.sh"
echo "   - Medium model configured for network access (0.0.0.0)"
echo "   - Accessible from other machines on the network"
echo "   - Usage: ./run_server_network.sh [options]"
echo ""

echo "9. run_server_fast.sh"
echo "   - Small model optimized for maximum speed"
echo "   - Fastest processing with lower accuracy"
echo "   - Usage: ./run_server_fast.sh [options]"
echo ""

echo "10. run_server_accurate.sh"
echo "    - Large-v3 model with diarization for maximum accuracy"
echo "    - Highest accuracy with speaker identification"
echo "    - Usage: ./run_server_accurate.sh [options]"
echo ""

echo "🛠️  Management Commands (for all scripts):"
echo "=========================================="
echo "  --stop                    # Stop the running server"
echo "  --restart                 # Restart the server"
echo "  --status                  # Check server status"
echo "  --help                    # Show help for specific script"
echo ""

echo "📊 Model Comparison:"
echo "==================="
echo "  small      - Fastest, lowest accuracy, ~1GB RAM"
echo "  medium     - Balanced, good accuracy, ~5GB RAM"
echo "  large-v3   - Highest accuracy, multilingual, ~10GB RAM"
echo ""

echo "🔧 Features:"
echo "============"
echo "  Diarization    - Speaker identification (slower but more detailed)"
echo "  Language       - Auto-detection or specific language (en, id, es, etc.)"
echo "  Network Access - localhost (default) or 0.0.0.0 (network accessible)"
echo "  Background     - All scripts run in background with PID management"
echo "  Logging        - All logs saved to ./logs/YYYYMMDDHHMISS.log"
echo ""

echo "💡 Usage Examples:"
echo "=================="
echo "  # Start with default settings"
echo "  ./run_server_medium.sh"
echo ""
echo "  # Start with custom port"
echo "  ./run_server_english.sh --port 9002"
echo ""
echo "  # Start with specific language"
echo "  ./run_server_multilingual.sh --language es"
echo ""
echo "  # Stop any running server"
echo "  ./run_server_medium.sh --stop"
echo ""
echo "  # Check server status"
echo "  ./run_server_medium.sh --status"
echo ""
echo "  # View logs"
echo "  tail -f ./logs/YYYYMMDDHHMISS.log"
echo ""

echo "🎯 Recommended Use Cases:"
echo "========================"
echo "  Real-time applications:     run_server_fast.sh"
echo "  General purpose:           run_server_medium.sh"
echo "  High accuracy needed:      run_server_accurate.sh"
echo "  English only:              run_server_english.sh"
echo "  Multilingual with speakers: run_server_multilingual.sh"
echo "  Network access needed:     run_server_network.sh"
echo "  Indonesian with speakers:  run_server_with_diarization_large_id.sh"
echo ""

echo "📝 Notes:"
echo "========"
echo "- All scripts use H100 GPU optimization"
echo "- Background execution with PID management"
echo "- Logs are automatically saved to ./logs/"
echo "- Use --help with any script for detailed options"
echo "- Network scripts require proper firewall configuration"
echo "" 