#!/bin/bash

# WhisperLiveKit Indonesian Server Scripts Overview
# Lists all available Indonesian-specific run scripts with their configurations

echo "🇮🇩 WhisperLiveKit Indonesian Server Scripts Overview"
echo "===================================================="
echo ""
echo "Available Indonesian-specific run scripts:"
echo ""

echo "📋 Indonesian Script List:"
echo "=========================="
echo ""

echo "1. run_server_id_small.sh"
echo "   - Small model (fastest processing, lower accuracy)"
echo "   - Language: Indonesian (id)"
echo "   - Diarization: enabled (speaker identification)"
echo "   - Usage: ./run_server_id_small.sh [options]"
echo ""

echo "2. run_server_id_medium.sh"
echo "   - Medium model (balanced speed/accuracy)"
echo "   - Language: Indonesian (id)"
echo "   - Diarization: enabled (speaker identification)"
echo "   - Usage: ./run_server_id_medium.sh [options]"
echo ""

echo "3. run_server_id_large.sh"
echo "   - Large-v3 model (highest accuracy, multilingual)"
echo "   - Language: Indonesian (id)"
echo "   - Diarization: enabled (speaker identification)"
echo "   - Usage: ./run_server_id_large.sh [options]"
echo ""

echo "4. run_server_id_network.sh"
echo "   - Medium model configured for network access (0.0.0.0)"
echo "   - Language: Indonesian (id)"
echo "   - Diarization: enabled (speaker identification)"
echo "   - Accessible from other machines on the network"
echo "   - Usage: ./run_server_id_network.sh [options]"
echo ""

echo "5. run_server_id_accurate.sh"
echo "   - Large-v3 model with diarization for maximum accuracy"
echo "   - Language: Indonesian (id)"
echo "   - Diarization: enabled (speaker identification)"
echo "   - Usage: ./run_server_id_accurate.sh [options]"
echo ""

echo "6. run_server_id_very_accurate.sh"
echo "   - Large-v3 model with enhanced quality settings"
echo "   - Language: Indonesian (id)"
echo "   - Diarization: enabled (speaker identification)"
echo "   - Enhanced settings: best_of=5, beam_size=5, temperature=0.0"
echo "   - Maximum quality for professional content"
echo "   - Usage: ./run_server_id_very_accurate.sh [options]"
echo ""

echo "7. run_server_id_very_fast.sh"
echo "   - Small model optimized for maximum speed"
echo "   - Language: Indonesian (id)"
echo "   - Diarization: enabled (speaker identification)"
echo "   - Fastest processing with lower accuracy"
echo "   - Usage: ./run_server_id_very_fast.sh [options]"
echo ""

echo "8. run_server_id_simul.sh"
echo "   - Medium model optimized for real-time processing"
echo "   - Language: Indonesian (id)"
echo "   - Diarization: enabled (speaker identification)"
echo "   - Simultaneous processing for live streaming"
echo "   - Usage: ./run_server_id_simul.sh [options]"
echo ""

echo "🛠️  Management Commands (for all scripts):"
echo "=========================================="
echo "  --stop                    # Stop the running server"
echo "  --restart                 # Restart the server"
echo "  --status                  # Check server status"
echo "  --help                    # Show help for specific script"
echo ""

echo "📊 Indonesian Model Comparison:"
echo "=============================="
echo "  small      - Fastest, lowest accuracy, ~1GB RAM"
echo "  medium     - Balanced, good accuracy, ~5GB RAM"
echo "  large-v3   - Highest accuracy, multilingual, ~10GB RAM"
echo ""

echo "🔧 Indonesian-Specific Features:"
echo "==============================="
echo "  Language       - Indonesian (id) optimized"
echo "  Diarization    - Speaker identification ENABLED BY DEFAULT"
echo "  Network Access - localhost (default) or 0.0.0.0 (network accessible)"
echo "  Background     - All scripts run in background with PID management"
echo "  Logging        - All logs saved to ./logs/YYYYMMDDHHMISS.log"
echo ""

echo "💡 Usage Examples:"
echo "=================="
echo "  # Start with default settings (includes speaker identification)"
echo "  ./run_server_id_medium.sh"
echo ""
echo "  # Start with custom port"
echo "  ./run_server_id_large.sh --port 9002"
echo ""
echo "  # Start with speaker identification (already enabled by default)"
echo "  ./run_server_id_accurate.sh"
echo ""
echo "  # Stop any running server"
echo "  ./run_server_id_medium.sh --stop"
echo ""
echo "  # Check server status"
echo "  ./run_server_id_medium.sh --status"
echo ""
echo "  # View logs"
echo "  tail -f ./logs/YYYYMMDDHHMISS.log"
echo ""

echo "🎯 Recommended Use Cases for Bahasa Indonesia:"
echo "============================================="
echo "  Real-time applications:     run_server_id_very_fast.sh"
echo "  General purpose:           run_server_id_medium.sh"
echo "  High accuracy needed:      run_server_id_accurate.sh"
echo "  Professional content:      run_server_id_very_accurate.sh"
echo "  Live streaming:           run_server_id_simul.sh"
echo "  Network access needed:     run_server_id_network.sh"
echo "  Fast processing:          run_server_id_small.sh"
echo "  Balanced approach:        run_server_id_large.sh"
echo ""

echo "📝 Notes:"
echo "========"
echo "- All scripts use H100 GPU optimization"
echo "- Background execution with PID management"
echo "- Logs are automatically saved to ./logs/"
echo "- Use --help with any script for detailed options"
echo "- Network scripts require proper firewall configuration"
echo "- Indonesian language optimization for better accuracy"
echo "- Diarization (speaker identification) is ENABLED BY DEFAULT"
echo "- All scripts optimized for Indonesian multi-speaker conversations"
echo "" 